### ISSUE TITLE
TEA Book Checklist

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#233]
- [x] Book has a preface
- [x] End of book pages are composite chapters
- [ ] All learning objectives have been converted to have h3 headers
- [ ] All modules/pages start with h3 header
- [x] hasCompositeChapter is set to true (for Preface, Appendix nesting)
- [x] All solutions are removed
- [x] Index should be removed

**Comment by tomjw64** [comment]
HS Stats:
- [ ] Waiting for content on Preface
- [ ] Waiting for section/h3 structure for content

**Comment by tomjw64** [comment]
AP Physis:
- [ ] No Preface
- [ ] Only some pages have section/h3 structure
