### ISSUE TITLE
Enable all feature flags for intro-business

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#540]
## https://github.com/Connexions/cnx-recipes/blob/petty.pegasus/FEATURES.md

- [x]  **sup-footnote-call**: issue #473

- [x]  **trash-empty-table-captions**: issue #434

- [x]  **exercise-container**: issue #454

- [x] **delete-link-in-equation-number**: issue #521

- [x]  **table-summaries-are-captions**: issue #407

- [x]  **preface-has-captions**: issue #455

**Comment by Stackblocks** [comment]
## sup-footnote-call
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ee8de51a-98d4-4f60-9c58-daf695145a66)
## trash-empty-table-captions
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ac70044c-f7c1-4bc9-92a2-7cc3eec2e573)
## exercise-container
n/a
## delete-link-in-equation-number
n/a
## table summaries are captions
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4d6bb121-a66f-405f-8c05-6b55b471053f)
# preface-has-captions
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8e49ff79-1bc2-4aa3-be40-7dc791a8224d)
